#!/bin/bash
directory=~/Documents/Education/research-papers
RG_PREFIX="rga --files-with-matches --text --glob '*.pdf'"
initial_query="${*:-}"

pdf_files=$(find $directory -name "*.pdf")

input=$(
    $RG_PREFIX '$initial_query' $directory \
    | fzf --print-query \
    --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} '$directory' || true" \
    --preview-window="70%:wrap" \
)
# Does it include .pdf? then we probably want to open it.
if [[ "$input" == *".pdf"* ]]; then
    file=$(echo "$input" | rg '/.*')
    not_the_file=$(echo "$input" | rg '^[^/]*')

    query=$(echo -n "$not_the_file" | head -1 |tr -d '\n')
    zathura "$file" --find "$query"
elif [[ -n "$input" ]]; then
    # If it's not empty and it's not a pdf, then it must be a web query.
    query="${input// /+}"
    firefox "https://duckduckgo.com/?q=$query"
fi
